version: '2'
services:
  # HUSTOJ
  hustoj:
    build:
      context: ./build/hustoj
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/data:rw
      - ./data/config/nginx/:/etc/nginx/sites-enabled:rw
      - ./data/config/php5/:/etc/php5/fpm:rw
      - ./data/config/db_info:/home/judge/src/web/include:rw
    stdin_open: true
    tty: true

